blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name= 'posts'),
    path('<int:post_id>', post_detail, name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date= models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts= Post.objects.all()
    return render(request, 'posts.html',{'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post":post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
def home(request):
    project = Project.objects.all()
    return render(request, 'home.html',{'projects':project})

blog/templates/post_detail.html
{% extends 'layout.html' %} {% block content %}

<h2>{{post.title}}</h2>
<h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

<img src="{{post.image.url}}" alt="{{post.title}}"class="img-fluid"/>

<div class="my-4">
    <p>{{post.description|safe}}</p>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{%block content %}
<h1>Posts</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-bod bg-black text-light">
        <div class="row">
            <div class="col-3">
           <img src="{{post.image.url}}" alt="{{post.title}}"class="img-fluid"/> 
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
            <p>{{post.description|safe|truncatechars:100}}</p>
            <p>{{post.date|date:'M d Y'|upper}}</p>
                
            <a href="{% url 'blog:post_detail' post.id %}"class="btn btn-primary">{{post.title}}</a>
               
            </div>
        </div>
    </div>    
</div>
{% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{%block content %}

{% load static %}



<header class="row bg-black">
    <div class="col-md-4">
    <img src="{% static 'portfolio/profile.jpeg' %}" alt="">
    </div>

    <div class="col-md-8 my-auto">
        <h1> Yo soy <strong> Luis Prado</strong></h1>
        <h3> Yo programo en Visual Studio Code </h3>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Autem, a! Enim perspiciatis minus odit maiores alias quasi aliquam consectetur! Nam, sed tempore. 
        Consequuntur quas ducimus, cumque totam eveniet maiores animi commodi soluta adipisci eius iste. 
        Culpa id perferendis quasi praesentium ipsa cupiditate minus est dolor dignissimos. 
        Quae vero amet sit placeat veritatis omnis necessitatibus enim id voluptatum! 
        Aliquam minus alias veritatis, excepturi deserunt dicta magni! Voluptatem, dolorem eum odio inventore sunt pariatur. 
        Modi obcaecati cum labore quia voluptates iste! Sint rem voluptas modi a obcaecati minima id illum quod sapiente, 
        magnam temporibus deserunt tenetur illo aperiam harum cum aliquam esse? 
        </p>
    <a 
    href="{% static 'portfolio/cv.pdf' %}" 
    class="btn btn-primary btn-lg rounded-o my-3"
    >Descargar CV</a>

    </div>
</header>

<div class="row my-4 text-center">

    <h3>Mi proyecto</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, reiciendis.</p>

{% for project in projects %}

<div class="col md-4 p-4">
    <div class="card bg-black card-project text-light">
        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top"/>
        <div class="card-body">

        <h2>{{project.title}}</h2> <p>{{project.description}}</p>
        

        {% if project.url %}
        <a href="{{project.url}}"
        class= "btn btn-light rounded-0 btn-sm"
        target="_blank">{{project.url}}</a>

        {% endif %}
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

</div>

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

    <div class="container p-4">

    {% block content %}
    {% endblock %}
    
    </div>
</body>

</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Luis Prado</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}"target ="_blank">Descargar CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>